# Generated by Codex on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("en_revision", "En revision"),
                            ("confirmado", "Confirmado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="recibido",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("recibido_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "orden_produccion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orden_venta",
                        to="produccion.ordenproduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de venta",
                "verbose_name_plural": "Ordenes de venta",
                "ordering": ["-recibido_en"],
            },
        ),
    ]

