# Generated by Django 6.0.3 on 2026-03-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_detalle', to='materiales.material')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Detalle de receta',
                'verbose_name_plural': 'Detalles de receta',
                'ordering': ['id'],
                'unique_together': {('receta', 'material')},
            },
        ),
    ]
