# Generated by Codex on 2026-03-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receta",
            name="actualizado_en",
        ),
        migrations.RemoveField(
            model_name="receta",
            name="creado_en",
        ),
    ]
